config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'emotes#index'
  get 'signup' => 'users#new'
  resources :emotes
  get 'login/' => 'sessions#new'
  post 'login/' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/emote.rb
class Emote < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_reader :password

  def password=(unecrypted_password)
    unless unecrypted_password.empty?
      @password = unecrypted_password
      self.password_digest = BCrypt::Password.create(unecrypted_password)
    end
  end

  def authenticate(unecrypted_password)
    if BCrypt::Password.new(self.password_digest) == unecrypted_password
      return self
    else
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  

  private


end

app/controllers/emotes_controller.rb
class EmotesController < ApplicationController
  before_action :set_emote, only: [:show, :edit, :update, :destroy]
  require 'net/http'
  require 'json'
  # GET /emotes
  # GET /emotes.json
  def index
    @emotes = Emote.all
    # @students = HTTParty.get("https://api.github.com/teams/1365559/members?access_token=ac26a9be4540039b4692beea74209de0a520d2bd")
    # @gifs = HTTParty.get("https://api.giphy.com/v1/gifs/search?q=why&limit=1&api_key=dc6zaTOxFJmzC")
    url = "https://api.giphy.com/v1/gifs/search?q=why&limit=1&api_key=dc6zaTOxFJmzC"
    @resp = HTTParty.get(url)
    buffer = @resp.body
    result = JSON.parse(buffer)
    @gifs = result
    @gifs = @gifs["data"][0]["images"]["fixed_height"]["url"]

  end

  # GET /emotes/1
  # GET /emotes/1.json
  def show
  end

  # GET /emotes/new
  def new
    @emote = Emote.new
  end

  # GET /emotes/1/edit
  def edit
  end

  # POST /emotes
  # POST /emotes.json
  def create
    @emote = Emote.new(emote_params)

    respond_to do |format|
      if @emote.save
        format.html { redirect_to @emote, notice: 'Emote was successfully created.' }
        format.json { render :show, status: :created, location: @emote }
      else
        format.html { render :new }
        format.json { render json: @emote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emotes/1
  # PATCH/PUT /emotes/1.json
  def update
    respond_to do |format|
      if @emote.update(emote_params)
        format.html { redirect_to @emote, notice: 'Emote was successfully updated.' }
        format.json { render :show, status: :ok, location: @emote }
      else
        format.html { render :edit }
        format.json { render json: @emote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emotes/1
  # DELETE /emotes/1.json
  def destroy
    @emote.destroy
    respond_to do |format|
      format.html { redirect_to emotes_url, notice: 'Emote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emote
      @emote = Emote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emote_params
      params.require(:emote).permit(:command, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email])

    if user && user.authenticate(params[:login][:password])
      log_in user
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emotes_helper.rb
module EmotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/emotes/_form.html.erb
<%= form_for(@emote) do |f| %>
  <% if @emote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emote.errors.count, "error") %> prohibited this emote from being saved:</h2>

      <ul>
      <% @emote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :command %><br>
    <%= f.text_field :command %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emotes/edit.html.erb
<h1>Editing Emote</h1>

<%= render 'form' %>

<%= link_to 'Show', @emote %> |
<%= link_to 'Back', emotes_path %>

app/views/emotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>GIPHY API integration</h1>
<p>
  <%= @gifs %>
</p>

<img src='<%= @gifs %>' alt="" />


<h1>Listing Emotes</h1>

<table>
  <thead>
    <tr>
      <th>Command</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emotes.each do |emote| %>
      <tr>
        <td><b><%= emote.command %><b></td>
        <td><%= emote.url %></td>
        <td>
        </td>
        <td>
          <img src="<%= emote.url %>" width="480" height="193" frameBorder="0" class="giphy-embed" allowFullScreen></img>
        </td>
        <td><%= link_to 'Show', emote %></td>
        <td><%= link_to 'Edit', edit_emote_path(emote) %></td>
        <td><%= link_to 'Destroy', emote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emote', new_emote_path %>

app/views/emotes/new.html.erb
<h1>New Emote</h1>

<%= render 'form' %>

<%= link_to 'Back', emotes_path %>

app/views/emotes/show.html.erb
<p id="notice"><%= notice %></p>

<img src="<%= @emote.url %>" width="480" height="193" frameBorder="0" class="giphy-embed" allowFullScreen></img>
<div class="ui big input">
  <input type="text" placeholder="<%= @emote.command %>">
</div>

<p>
  <strong>Command:</strong>
  <%= @emote.command %>
</p>

<p>
  <strong>Url:</strong>
  <%= @emote.url %>
</p>



<%= link_to 'Edit', edit_emote_path(@emote) %> |
<%= link_to 'Back', emotes_path %>

app/views/layouts/_navigation.html.erb
<nav>
  <% if logged_in? %>
  	<%= "You are currently logged in as: #{current_user.name}"%>
  	<%= link_to "Log out", logout_path, method: :delete %>
  <% else %>
  	<%= link_to "Log in", login_path, {:id => 'log-in-lnk'} %>
  	<%= link_to "Sign up", signup_path, {:id => 'sign-up-lnk'}  %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emotely</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <%= render partial: "layouts/navigation" %>
</header>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>